/* eslint-disable no-restricted-globals */

// This service worker can be customized. See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate } from "workbox-strategies";

clientsClaim();

// Precache all of the assets generated by the build process. This is the
// entire game — JS bundle, CSS, HTML shell, the locations catalog, and the
// icons imported from src — so a single successful online visit is enough
// for the app to keep working with zero connectivity afterwards (offline
// desert-trip friendly).
precacheAndRoute(self.__WB_MANIFEST);

// Set up an app shell-style router. This allows deep-linking (e.g. directly
// opening "/single" while offline) to always resolve to the cached index.html,
// since this is a fully client-side-routed single-page app.
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(
  ({ request, url }) => {
    if (request.mode !== "navigate") return false;
    if (url.pathname.startsWith("/_")) return false;
    if (url.pathname.match(fileExtensionRegexp)) return false;
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html")
);

// Runtime-cache any other same-origin image requests (e.g. the generated
// icons) with a stale-while-revalidate strategy so they load instantly and
// still refresh in the background whenever a connection is available.
registerRoute(
  ({ url }) => url.origin === self.location.origin && /\.(?:png|jpg|jpeg|svg|gif|ico)$/.test(url.pathname),
  new StaleWhileRevalidate({
    cacheName: "images",
    plugins: [new ExpirationPlugin({ maxEntries: 50 })],
  })
);

// Workbox's InjectManifest only knows about files that webpack actually
// processes (JS/CSS bundles, and anything imported from src/, like the
// NavBar logo). The PWA icons and manifest.json are plain, stable-named
// files copied straight from public/, so nothing above ever sees them —
// cache them explicitly here so "Add to Home Screen" and the app icon work
// with zero connectivity too.
const EXTRA_PRECACHE_URLS = [
  `${process.env.PUBLIC_URL}/manifest.json`,
  `${process.env.PUBLIC_URL}/favicon.ico`,
  `${process.env.PUBLIC_URL}/logo192.png`,
  `${process.env.PUBLIC_URL}/logo512.png`,
];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open("spyfall-extra-assets").then((cache) => cache.addAll(EXTRA_PRECACHE_URLS)));
});

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});
